# Generated by Django 5.1 on 2024-09-01 06:40

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visa_validation', 'Visa Validation'), ('social_security', 'Social Security'), ('bank_account', 'Bank Account'), ('transportation', 'Transportation'), ('caf_housing_allowance', 'CAF Housing Allowance')], max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='how_did_you_hear_about_us',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='city_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='contact',
            name='services_needed',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='core.service'),
        ),
    ]
